### ISSUE TITLE
VNC startup time long for ROS 2

### ISSUE THREAD

**Issue by schmerl** [TheRobotCooperative/TheRobotCooperative#52]
The `/startup-vnc.sh` for the ROS 2 container takes a long time to start. This is because it has to do `chown -R root:root /root` as the first command.

With DDS installed, a fair number of files (~3500) are in the `/root/rti_workspace` directory now. This causes the chown command to take about 30 seconds to complete.

Two options: 

1. Move the chown command to the Dockerfile for ROS2 (although all files in` /root` seem to be owned by `root` already)
2. Find a way to move the location of the `rti_workspace`

**Comment by schmerl** [comment]
I created a branch for working on this: `bugfix/52`

**Comment by ChrisTimperley** [comment]
Nice catch. I'm not actually sure why we run the `chown` command there. It makes sense to do the `chown` operation once, as part of the image build process, rather than run it for each `/startup-vnc.sh` call.
